### ISSUE TITLE
require 'json' missing from client.rb

### ISSUE THREAD

**Issue by logicminds** [chef-partners/vmware-vra-gem#21]
You are using to_json which requires loading the json library.  Without this users are required to have `require 'json'` in their code/script.

```
`generate_bearer_token': undefined method `to_json' for #<Hash:0x007fbe8c6c3728> (NoMethodError)
	from .rubygems/gems/vmware-vra-1.5.1/lib/vra/client.rb:87:in `authorize!'
	from .rubygems/gems/vmware-vra-1.5.1/lib/vra/client.rb:133:in `http_get'
	from .rubygems/gems/vmware-vra-1.5.1/lib/vra/client.rb:146:in `http_get!'
	from .rubygems/gems/vmware-vra-1.5.1/lib/vra/client.rb:156:in `block in 

```

**Comment by adamleff** [comment]
@logicminds, thanks for this issue report. This never surfaces before because most of our users are consuming this gem through Chef's `knife` command which already had required the `json` library.

Since we're already using `FFI_Yajl` for our JSON encoding, rather than `require 'json'` I switched to use `FFI_Yajl::Encoder` in PR #22. Once we merge this in, I'll release a new version of the gem. In the meantime, you can use my branch `adamleff/use-ffiyajl-encoder` via Bundler if you'd like.

Thanks again for the issue report.

**Comment by logicminds** [comment]
Just curious why you are not using ruby core library to parse json?

**Comment by adamleff** [comment]
Speed, primarily. While negligible for a library like this, the primary intention of creating this gem was use in other Chef tooling which is already using ffi_yajl for JSON parse/encode speed, so I decided to use it here as well for consistency.

**Comment by adamleff** [comment]
@logicminds v1.5.2 of this gem has been released to RubyGems. Thanks again for your report and my apologies for the issue!
